### ISSUE TITLE
Add ajax call to AWS for email in form

### ISSUE THREAD

**Issue by antonioortegajr** [antonioortegajr/idxInternshipNov2018#5]
Current form doesn't go anywhere. Adding a Amazon Web Service and a ajax request will make it so you can receive emails.

Will be based on this article: https://codehabitude.com/2016/04/05/forms-to-emails-using-aws-lambda-api-gateway/

And this gist: https://gist.github.com/tgroshon/04b94aee6331bb65f05f4e0d7ff2e8bd

**Comment by DavijEllis** [comment]
Will fix in own repository. https://davijellis.github.io/idxInternshipNov2018/
